# Generated by Django 4.2.7 on 2024-07-05 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacionuno', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dueños',
            new_name='Propietarios',
        ),
    ]
